# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: client build

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

env:
  BUCKET: 'zeze-build/front'
  BUILD_DIR: 'static'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install 
      run: |
        cd client
        yarn install
    - name: yarn build
      run: |
        cd client
        yarn build
      env:
        CI: 'false'
    - name: zip artifacts
      run: |
        mkdir ${BUILD_DIR}
        cp -r ./client/build/* ./${BUILD_DIR}
        zip -r ${BUILD_DIR}.zip ./client/build/*
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ${BUILD_DIR}.zip s3://$BUCKET/build/${BUILD_DIR}.zip --acl public-read-write
      
